docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: introduction.md
    - Reference:
        - Translation: translation.md
        - 'View Helpers': view-helpers.md
        - Filters: filters.md
        - Validators:
            - 'Standard Validators': validators.md
            - DateTime: validators/date-time.md
            - IsInt: validators/is-int.md
            - PhoneNumber: validators/phone-number.md
            - PostCode: validators/post-code.md
site_name: laminas-i18n
site_description: 'Provide translations for your application, and filter and validate internationalized values.'
repo_url: 'https://github.com/laminas/laminas-i18n'
extra:
    project: Components
