docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: introduction.md
    - Reference:
        - Translation: translation.md
        - 'View Helpers': view-helpers.md
        - Filters: filters.md
        - Validators:
            - Introduction: validators/introduction.md
            - Alnum: validators/alnum.md
            - Alpha: validators/alpha.md
            - DateTime: validators/date-time.md
            - IsFloat: validators/is-float.md
            - IsInt: validators/is-int.md
            - PhoneNumber: validators/phone-number.md
            - PostCode: validators/post-code.md
    - 'Application Integration':
        - 'Stand-Alone': application-integration/stand-alone.md
    - Migration:
        - 'Migration from Versions prior to 2.4': migration/migration-to-v2.4.md
site_name: laminas-i18n
site_description: 'Provide translations for your application, and filter and validate internationalized values.'
repo_url: 'https://github.com/laminas/laminas-i18n'
extra:
    project: Components
