docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: introduction.md
    - Translation: translation.md
    - Translator:
        - Caching: translator/caching.md
        - Factory: translator/factory.md
        - 'Format Examples': translator/format-examples.md
    - Filters:
        - Introduction: filters/introduction.md
        - Alnum: filters/alnum.md
        - Alpha: filters/alpha.md
        - NumberFormat: filters/number-format.md
        - NumberParse: filters/number-parse.md
    - Reference:
        - Validators:
            - Introduction: validators/introduction.md
            - Alnum: validators/alnum.md
            - Alpha: validators/alpha.md
            - DateTime: validators/date-time.md
            - IsFloat: validators/is-float.md
            - IsInt: validators/is-int.md
            - PhoneNumber: validators/phone-number.md
            - PostCode: validators/post-code.md
    - 'View Helpers':
        - Introduction: view-helpers/introduction.md
        - CurrencyFormat: view-helpers/currency-format.md
        - DateFormat: view-helpers/date-format.md
        - NumberFormat: view-helpers/number-format.md
        - Plural: view-helpers/plural.md
        - Translate: view-helpers/translate.md
        - TranslatePlural: view-helpers/translate-plural.md
    - 'Application Integration':
        - 'Stand-Alone': application-integration/stand-alone.md
    - Migration:
        - 'Migration from Versions prior to 2.4': migration/migration-to-v2.4.md
    - '_hidden-legacy-page-links':
        - '_filters': filters.md
        - '_validators': validators.md
        - '_view-helpers': view-helpers.md
site_name: laminas-i18n
site_description: 'Provide translations for your application, and filter and validate internationalized values.'
repo_url: 'https://github.com/laminas/laminas-i18n'
extra:
    project: Components
